---
baseurl: https://forestry.io/docs/
languagecode: en-us
pluralizelisttitles: false
theme: forestry-doc-theme
title: Forestry Docs 
menu:
  main:
    - name: "Pricing"
      url: "http://forestry.io/plans/"
      weight: 1
    - name: "Docs"
      url: "http://forestry.io/docs/"
      weight: 2
    - name: "Blog"
      url: "http://forestry.io/blog"
      weight: 3
  footer:
    - name: "Terms"
      url: "http://forestry.io/terms/"
      weight: 1
    - name: "Privacy"
      url: "http://forestry.io/privacy/"
      weight: 2
    - name: "Careers"
      url: "http://forestry.io/careers/"
      weight: 3
  getting_started:
  - name: Support and help
    weight: 3
params:
  description: "A static site cms generator for Hugo and Jekyll"
  twitter_card: ""
  author:
    - bio: "CEO and Co-founder of <a href='https://forestry.io' title='Forestry.io CMS'>Forestry.io</a>. Web developer, recovering freelancer."
      img: "/images/Scott_Gallant.jpg"
      link: "https://twitter.com/scottgallant"
      name: "Scott Gallant"
      twitter: "https://twitter.com/scottgallant"
sitemap:
  ChangeFreq: ''
  Filename: sitemap.xml
  Priority: "-1"
